# Generated by Django 3.1.14 on 2023-01-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20230125_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание покемона'),
        ),
    ]
