# Generated by Django 3.1.14 on 2023-01-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20230126_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_evolution_next', to='pokemon_entities.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_evolution_previous', to='pokemon_entities.pokemon'),
        ),
    ]
