# Generated by Django 3.1.14 on 2023-01-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20230126_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evolution_id',
            new_name='next_evolution',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution_id',
            new_name='previous_evolution',
        ),
    ]
