# Generated by Django 3.1.14 on 2023-01-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20230127_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_evolution_previous', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционирует'),
        ),
    ]
