# Generated by Django 3.1.14 on 2023-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20230127_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание покемона'),
        ),
    ]
